### ISSUE TITLE
ERR! message is confusing

### ISSUE THREAD

**Issue by ofthelake** [StepicOrg/Stepik-Studio#23]
an ERR! message appears next to recorded videos' lengths if they differ by more than few seconds, to show that something went wrong with one of the videos -- and that's OK.
but somehow it also appears if videos' lengths are exactly the same, which is perfectly normal -- and that disturbs users a lot.

**Comment by vyahhi** [comment]
maybe fixed in https://github.com/StepicOrg/Stepik-Studio/commit/594f2dbdf8fc36e83469ab420842c8c6e3c4842a

**Comment by vyahhi** [comment]
waiting for example from @ofthelake, so we can verify that this bug is fixed
