### ISSUE TITLE
make error messages user-friendly

### ISSUE THREAD

**Issue by ofthelake** [StepicOrg/Stepik-Studio#27]
currently, you can only get a short "server error" message or some Django error log (not sure how it's called properly), both of which are not helping our regular user.

1. we should add some piece of advice to our users: what to do once they've got this error
2. and the error logs themselves we should send to someone who's able to make sense of them

**Comment by vyahhi** [comment]
Servers errors should not appear. 
If they are, then see https://github.com/StepicOrg/Stepik-Studio/issues/38.

**Comment by vyahhi** [comment]
After #38 make 5xx error pages more user-friendly.

**Comment by vyahhi** [comment]
Idea: 5xx page which says "Sorry it's a bug, please send this error log to developers <textarea>...</textarea>"

**Comment by vyahhi** [comment]
Fixed in https://github.com/StepicOrg/Stepik-Studio/pull/39
