### ISSUE TITLE
IndexError at /course/86/lesson/622/step/2708/

### ISSUE THREAD

**Issue by vyahhi** [StepicOrg/Stepik-Studio#36]
```
list index out of range
Exception Location: stepicstudio\FileSystemOperations\action.py in get_length_in_sec, line 184

...

duration_string = [x.decode("utf-8") for x in result.stdout.readlines() if "Duration" in x.decode('utf-8')][0]
```

(in MSK)

**Comment by vyahhi** [comment]
Looks like fixed 3 years ago in https://github.com/StepicOrg/Stepik-Studio/commit/60cc177db57755a1ca862466a0bc0e2b20f5ff31

**Comment by mehanig** [comment]
MSK server was using legacy version dye to issues with BlackMagic card drivers and wasn't updated to this commit, I suppose.

**Comment by vyahhi** [comment]
@mehanig do you remember what kind of problems were in MSK with BlackMagic? Haven't we have the same hardware in SPb without any problems?

**Comment by pospelov14203** [comment]
MSK server successfully updated, there are no problems with drivers or ffmpeg, no error are thrown.
